-- =============================================================================
-- Flavour Field Lab — demo seed data (spec §32)
-- 8 realistic FICTIONAL field notes. is_demo = true on every row; the app UI
-- must surface a "DEMO DATA" label wherever these are shown, and no fictional
-- farmer/producer name here should ever be presented as a real contact.
--
-- IMPORTANT: field_notes.researcher_id has a foreign key to auth.users, and
-- Supabase Auth users can't be created from plain SQL. Sign up once in the
-- app first (or via the Supabase Auth dashboard), THEN run this file — it
-- attaches every demo note to the earliest-created auth user, which will be
-- you in a fresh project.
--
-- This file only inserts the RAW note content (exactly what a researcher
-- would type into "Capture Field Note"). It deliberately does NOT insert
-- observations / sources / research questions / R&D opportunities — those
-- are generated by running the real AI pipeline over this raw text via:
--     npm run seed:analyze
-- so the demo data is produced by the exact same code path as a live save,
-- not hand-duplicated.
-- =============================================================================

with researcher as (
  select id from auth.users order by created_at asc limit 1
),
ingredient_rows as (
  insert into public.ingredients (name, category)
  values
    ('Jaggery', 'Sugar / Sweetener'),
    ('Mango (heirloom, unnamed local variety)', 'Fruit'),
    ('Kokum', 'Fruit'),
    ('Kodo millet', 'Millet'),
    ('Mawa (Khoa)', 'Dairy'),
    ('Black rice (Chak-hao)', 'Grain'),
    ('Palm jaggery (Karupatti)', 'Sugar / Sweetener'),
    ('Rice beer starter culture (unnamed local ferment)', 'Fermentation culture')
  on conflict (name) do update set name = excluded.name
  returning id, name
)
insert into public.field_notes (
  title, date, researcher_id, researcher_name, country, state, district, gps,
  ingredient_id, ingredient_name, ingredient_category, raw_text,
  producer_name, producer_org, producer_contact, relationship_notes,
  avail_quantity, avail_price, avail_season, avail_harvest_period, avail_processing_period, avail_current,
  is_demo
)
select v.title, v.date::date, r.id, 'Meera Kulkarni (demo)', 'India', v.state, v.district, v.gps,
       ing.id, v.ingredient_name, v.ingredient_category::ingredient_category, v.raw_text,
       v.producer_name, v.producer_org, v.producer_contact, v.relationship_notes,
       v.avail_quantity, v.avail_price, v.avail_season, v.avail_harvest_period, v.avail_processing_period, v.avail_current,
       true
from researcher r
cross join (values
  (
    'Traditional jaggery producer near Kolhapur', '2026-03-14',
    'Maharashtra', 'Kolhapur', '16.70°N, 74.24°E',
    'Jaggery', 'Sugar / Sweetener',
    'Visited a jaggery producer near Kolhapur. They are making jaggery from local sugarcane. The jaggery was much darker than the commercial stuff and had a smoky caramel smell. They said the season starts around March and ends around April. The family has been doing this for three generations. They currently produce around 300kg per season.',
    'Local jaggery producer (name withheld — demo)', 'Family farm', 'Not recorded', 'Third generation producers; open to follow-up visits.',
    '~300kg / season', 'Not recorded', 'March–April', 'March–April', 'Same window, on-site', 'Seasonal, small-scale'
  ),
  (
    'Heirloom mango variety, orchard visit', '2026-02-02',
    'Karnataka', 'Shivamogga', '13.93°N, 75.57°E',
    'Mango (heirloom, unnamed local variety)', 'Fruit',
    'Small family orchard growing an old mango variety that isn''t sold commercially — mostly for home use and local barter. Fruit is smaller than Alphonso, very fibrous, intensely sour when unripe and turns sharply sweet-tart at full ripeness with a resinous, almost pine-like aroma. The farmer said the tree is at least 40 years old and they don''t know the variety name, just call it "naati mavu" (local mango). Fruiting window is short, maybe three weeks in April. They might be open to selling unripe fruit in bulk for pickling or fermentation experiments.',
    'Orchard family (demo)', 'Family orchard', 'Not recorded', 'Curious about non-food uses of unripe fruit; friendly and willing to talk.',
    'Unclear, low volume', 'Not discussed', 'April (short window)', '~3 weeks in April', 'N/A — sold fresh', 'Very limited, single tree'
  ),
  (
    'Kokum harvest, coastal homestead', '2026-05-20',
    'Goa', 'Canacona', '14.99°N, 74.05°E',
    'Kokum', 'Fruit',
    'Visited a homestead with several kokum trees along the backyard slope. Fruit is deep purple-red, very sour and slightly astringent, with a tannic, almost wine-like note. They sun-dry the rind for 5-6 days to make the dark, sticky dried kokum used in curries and a cooling summer drink called sol kadi. The woman running the household said kokum butter is also extracted from the seeds for skin use, not food. Harvest is roughly April to June. They sell dried kokum locally in small quantities, no formal packaging.',
    'Homestead owner (demo)', 'Independent household', 'WhatsApp shared (demo)', 'Very knowledgeable on traditional uses; good long-term contact.',
    'Small batches, kg-scale', '~₹400/kg dried (reported)', 'April–June', 'April–June', 'Sun-drying, 5–6 days', 'Local, informal sale'
  ),
  (
    'Indigenous kodo millet plot, dryland farm', '2025-11-08',
    'Karnataka', 'Chitradurga', '14.23°N, 76.40°E',
    'Kodo millet', 'Millet',
    'Farmer grows kodo millet as a rainfed crop, intercropped with pigeon pea. Grain is small, greyish, and has a distinctly earthy, nutty smell when roasted before milling. He mentioned that kodo millet needs almost no irrigation and survives poor soil, which is why his father kept growing it even after most neighbours switched to commercial crops. Traditional processing involves sun-drying, hand-pounding, and stone-milling. Yield seems modest — perhaps a few hundred kilograms per acre. He was not sure about exact numbers.',
    'Smallholder farmer (demo)', 'Independent farm', 'Not recorded', 'Proud of continuing his father''s practice; open to supplying test quantities.',
    'Uncertain, few hundred kg/acre (reported)', 'Not discussed', 'Sown monsoon, harvested Nov', 'October–November', 'Sun-dry, hand-pound, stone-mill', 'Small-scale, single farm'
  ),
  (
    'Mawa (khoa) production, roadside dairy unit', '2026-01-18',
    'Maharashtra', 'Nashik', '19.99°N, 73.79°E',
    'Mawa (Khoa)', 'Dairy',
    'Small roadside unit reducing buffalo milk over a wood fire in large flat pans, stirring continuously for hours until it forms a dense, slightly grainy solid — mawa. Smell is deeply roasted, almost toffee-like, much stronger than the packaged mawa I''ve had before. The person running the stall said they sell fresh every day, nothing is stored, and it doesn''t keep more than a couple of days without refrigeration. Demand spikes around festivals. He said wood-fire versus gas changes the taste, but I couldn''t independently confirm this.',
    'Roadside dairy vendor (demo)', 'Independent stall', 'Not recorded', 'Talkative, described process willingly; daily production, easy to revisit.',
    'Daily batch, small', '~₹320/kg (reported)', 'Year-round, festival spikes', 'N/A', 'Daily, wood-fire reduction', 'Fresh daily, no storage'
  ),
  (
    'Black rice (chak-hao) paddy field visit', '2025-12-03',
    'Manipur', 'Imphal East', '24.82°N, 93.95°E',
    'Black rice (Chak-hao)', 'Grain',
    'Visited a paddy field growing chak-hao, the aromatic black rice used traditionally in Manipuri chak-hao kheer (a dessert). Grain has a deep purple-black bran layer, and cooked rice has a distinctive sweet, nutty, almost grape-like aroma. The farmer''s family said this variety has been cultivated in the valley for generations and is considered sacred/ceremonial, used in festivals. It might have anthocyanin pigments responsible for the colour, though I''d need to confirm that. Harvest is around November-December, once a year.',
    'Farming family, Imphal valley (demo)', 'Family farm', 'Not recorded', 'Rice has ceremonial significance; approach sourcing with cultural sensitivity.',
    'Not quantified', 'Not discussed', 'Harvest Nov–Dec, once yearly', 'November–December', 'Traditional husking', 'Seasonal, once-yearly harvest'
  ),
  (
    'Palm jaggery (karupatti) production unit', '2026-04-22',
    'Kerala', 'Palakkad', '10.78°N, 76.65°E',
    'Palm jaggery (Karupatti)', 'Sugar / Sweetener',
    'Visited a small unit producing palm jaggery from toddy palm sap. Sap is collected early morning by climbers, boiled down the same day before it ferments. Karupatti is much darker than sugarcane jaggery, almost black, with a mineral, slightly bitter-smoky edge and less sweetness than I expected. The unit owner said sap has to be processed within hours or it turns alcoholic on its own — this happens naturally, no additive needed. Production is tightly tied to the number of active climbers available, which they said is shrinking every year as the skill dies out.',
    'Unit owner, Palakkad (demo)', 'Small production unit', 'Phone number shared (demo)', 'Concerned about disappearing climbing skill; open to collaboration on documentation.',
    'Variable, climber-dependent', '~₹250/kg (reported)', 'Year-round, weather dependent', 'Daily tapping', 'Same-day boiling, mandatory', 'Constrained by labour, declining'
  ),
  (
    'Wild rice-beer fermentation technique, hill village', '2025-10-11',
    'Nagaland', 'Zunheboto', '26.02°N, 94.52°E',
    'Rice beer starter culture (unnamed local ferment)', 'Fermentation culture',
    'Watched a household prepare a traditional fermented rice beverage using a starter cake made from rice flour and a mix of local leaves and herbs, dried and reused across batches. The finished drink was cloudy, mildly sour, slightly fizzy, with a funky, bready aroma — quite different from anything commercial. The woman said the starter recipe has been passed down from her mother and every household''s version tastes slightly different. She wasn''t willing to share the exact leaf mix. Fermentation takes about 3-5 days depending on weather. This could be a genuinely wild, undocumented mixed-culture ferment, but I have no lab data to confirm what''s actually in it.',
    'Household elder, Zunheboto (demo)', 'Independent household', 'Not recorded', 'Recipe is closely guarded family knowledge; relationship-building needed before any deeper access.',
    'Household scale only', 'Not for sale (reported)', 'Made year-round, weather-dependent speed', 'N/A', '3–5 day fermentation', 'Not commercially available'
  )
) as v(title, date, state, district, gps, ingredient_name, ingredient_category, raw_text, producer_name, producer_org, producer_contact, relationship_notes, avail_quantity, avail_price, avail_season, avail_harvest_period, avail_processing_period, avail_current)
join ingredient_rows ing on ing.name = v.ingredient_name;

-- =============================================================================
-- One demo producer record (KB §08) + linkage, and one demo decision_log
-- entry (KB §38), so the new tables have realistic FICTIONAL example data
-- rather than sitting empty. Private by default (visibility='PRIVATE').
-- =============================================================================
with researcher as (
  select id from auth.users order by created_at asc limit 1
),
new_producer as (
  insert into public.producers (
    researcher_id, name, region, village, ingredient_name, crop, variety,
    production_method, traditional_method, approximate_production, availability,
    season, processing, minimum_quantity, typical_price, contact,
    relationship_status, last_visited, notes, relationship_memory, visibility
  )
  select r.id, 'Local jaggery producer (name withheld — demo)', 'Kolhapur, Maharashtra', 'Not recorded (demo)',
    'Jaggery', 'Sugarcane', 'Local cultivar (unrecorded)',
    'Open-pan boiling', 'Third-generation family method', '~300kg / season', 'Seasonal',
    'March–April', 'Open-pan boiling, hand-poured moulds', 'Not discussed', 'Not recorded', 'Not recorded (demo)',
    'Warm, open to follow-up visits', '2026-03-14',
    'Third generation producers; darker, smokier jaggery than commercial equivalents.',
    jsonb_build_object(
      'previous_conversations', 'First visit — introduced by a local contact.',
      'sourcing_history', 'No purchases yet; sample only.',
      'quality_consistency', 'Unknown — single batch observed so far.'
    ),
    'PRIVATE'
  from researcher r
  returning id
)
update public.field_notes fn
set producer_id = np.id
from new_producer np
where fn.title = 'Traditional jaggery producer near Kolhapur' and fn.producer_id is null;

insert into public.decision_log (researcher_id, ingredient_name, decision, reason, potential, availability)
select r.id, 'Refined white sugar (commercial)', 'Rejected', 'Too common — no differentiation vs. any commercial supplier.', 'Low', 'High'
from researcher r;

-- After this runs, populate observations/sources/questions/opportunities with:
--   npm run seed:analyze
