/**
 * Runs the real AIService pipeline over the raw seed field notes inserted
 * by supabase/seed.sql, populating observations / sources / research
 * questions / R&D opportunities — the exact same derived data a live
 * "Save & Analyse" click produces. This keeps demo data honest: nothing
 * here is hand-authored output, it's generated by the same code path a
 * real researcher's capture goes through.
 *
 * Usage:
 *   1. Run supabase/schema.sql, then supabase/seed.sql, against your project.
 *   2. Set env vars in .env.local (see .env.example).
 *   3. npm run seed:analyze          # skips notes already analyzed
 *      npm run seed:analyze -- --force   # re-analyzes everything
 */
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

import { createClient } from '@supabase/supabase-js';
import { AIService } from '../src/lib/ai/service';
import type { AIAnalysis } from '../src/lib/ai/schema';
import type { FieldNote, FieldNoteDraft } from '../src/lib/types';

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !serviceKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local.');
  process.exit(1);
}
const supabase = createClient(url, serviceKey, { auth: { persistSession: false } });

const FORCE = process.argv.includes('--force');

function noteToDraft(note: FieldNote): FieldNoteDraft {
  return {
    title: note.title,
    date: note.date,
    researcherName: note.researcher_name || '',
    state: note.state,
    district: note.district,
    gps: note.gps || undefined,
    ingredientName: note.ingredient_name,
    ingredientCategory: note.ingredient_category,
    rawText: note.raw_text,
    producerName: note.producer_name || undefined,
    producerOrg: note.producer_org || undefined,
    producerContact: note.producer_contact || undefined,
    relationshipNotes: note.relationship_notes || undefined,
    availQuantity: note.avail_quantity || undefined,
    availPrice: note.avail_price || undefined,
    availSeason: note.avail_season || undefined,
    availHarvestPeriod: note.avail_harvest_period || undefined,
    availProcessingPeriod: note.avail_processing_period || undefined,
    availCurrent: note.avail_current || undefined
  };
}

async function persistAnalysis(fieldNoteId: string, analysis: AIAnalysis) {
  await supabase.from('field_observations').delete().eq('field_note_id', fieldNoteId);
  await supabase.from('sources').delete().eq('field_note_id', fieldNoteId);
  await supabase.from('research_questions').delete().eq('field_note_id', fieldNoteId);
  await supabase.from('rd_opportunities').delete().eq('field_note_id', fieldNoteId);

  await supabase.from('field_observations').insert(
    analysis.observations.map((o, i) => ({
      field_note_id: fieldNoteId,
      type: o.type,
      content: o.content,
      confidence: o.confidence,
      source: o.source,
      sort_order: i
    }))
  );

  if (analysis.sources.length) {
    await supabase.from('sources').insert(
      analysis.sources.map((s) => ({
        field_note_id: fieldNoteId,
        title: s.title,
        publisher: s.publisher,
        url: s.url || null,
        content: s.content,
        confidence: s.confidence,
        source_trust_class: s.source_trust_class,
        knowledge_level: s.knowledge_level
      }))
    );
  }

  await supabase.from('research_questions').insert(
    analysis.research_questions.map((q) => ({
      field_note_id: fieldNoteId,
      question: q.question,
      status: 'Open',
      priority: q.priority,
      evidence_required: q.evidence_required
    }))
  );

  await supabase.from('rd_opportunities').insert(
    analysis.rd_opportunities.map((op) => ({
      field_note_id: fieldNoteId,
      title: op.title,
      why: op.why,
      exploration: op.exploration,
      hypothesis_status: op.hypothesis_status,
      why_this: op.why_this,
      risks: op.risks,
      unknowns: op.unknowns,
      suggested_experiment: op.suggested_experiment,
      novelty_score: op.scores.novelty,
      feasibility_score: op.scores.feasibility,
      availability_score: op.scores.availability,
      brand_fit_score: op.scores.brand_fit,
      international_score: op.scores.international,
      confidence_score: op.scores.confidence
    }))
  );

  await supabase
    .from('field_notes')
    .update({ flavour_tags: analysis.flavour_tags, next_question: analysis.next_question, analyzed_at: new Date().toISOString() })
    .eq('id', fieldNoteId);

  const { data: note } = await supabase.from('field_notes').select('ingredient_id').eq('id', fieldNoteId).single();
  if (note?.ingredient_id) {
    const { data: ing } = await supabase.from('ingredients').select('flavour_profile').eq('id', note.ingredient_id).single();
    const merged = Array.from(new Set([...(ing?.flavour_profile || []), ...analysis.flavour_tags.map((t) => t.tag)])).slice(0, 12);
    await supabase.from('ingredients').update({ flavour_profile: merged }).eq('id', note.ingredient_id);
  }
}

async function main() {
  let query = supabase.from('field_notes').select('*').eq('is_demo', true);
  if (!FORCE) query = query.is('analyzed_at', null);
  const { data: notes, error } = await query;

  if (error) {
    console.error('Failed to fetch seed notes:', error.message);
    process.exit(1);
  }
  if (!notes || notes.length === 0) {
    console.log(FORCE ? 'No demo notes found. Run supabase/seed.sql first.' : 'All demo notes already analyzed. Use --force to re-run.');
    return;
  }

  console.log(`Analyzing ${notes.length} seed note(s) via AIService (${process.env.AI_PROVIDER || 'mock'} provider)…`);
  for (const note of notes as FieldNote[]) {
    process.stdout.write(`  - ${note.ingredient_name} (${note.district}, ${note.state})… `);
    try {
      const analysis = await AIService.analyzeFieldNote(noteToDraft(note));
      await persistAnalysis(note.id, analysis);
      console.log('done.');
    } catch (err) {
      console.log(`FAILED: ${err instanceof Error ? err.message : err}`);
    }
  }
  console.log('Seed analysis complete.');
}

main();
